//
// Generated by dtk
// Translation Unit: d_message_paper.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_message_paper.h"
#include "f_op/f_op_msg.h"
#include "d/d_meter.h"
#include "d/d_kankyo.h"
#include "m_Do/m_Do_controller_pad.h"
#include "m_Do/m_Do_ext.h"
#include "m_Do/m_Do_mtx.h"
#include "m_Do/m_Do_graphic.h"
#include "JSystem/J3DGraphAnimator/J3DModel.h"
#include "JSystem/J3DGraphBase/J3DTexture.h"
#include "JSystem/JUtility/JUTNameTab.h"
#include "JSystem/JKernel/JKRArchive.h"
#include "JSystem/JKernel/JKRExpHeap.h"
#include "d/d_drawlist.h"
#include "dolphin/os/OSCache.h"
#include "stdio.h"
#include <string.h>
#include "JSystem/J3DGraphLoader/J3DModelLoader.h"
#include "JSystem/J3DGraphLoader/J3DAnmLoader.h"
#include "JSystem/J2DGraph/J2DTextBox.h"
#include "JSystem/J2DGraph/J2DPicture.h"
#include "JSystem/J2DGraph/J2DScreen.h"
#include "JSystem/J2DGraph/J2DOrthoGraph.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "JAZelAudio/JAIZelBasic.h"

void dMsg3_messageDataInit(sub_msg3_class*, int);
u8 dMsg3_aimBrightness();
void dMsg3_textPosition(sub_msg3_class*, u8);
void dMsg3_yose_select(sub_msg3_class*, u8);
void dMsg3_setCharAlpha(sub_msg3_class*, u8);

/* 801EB128-801EB420       .text setDummyTexture__10dmsg3_3d_cFv */
void dmsg3_3d_c::setDummyTexture() {
    J3DModelData* modelData = mModel->getModelData();
    J3DTexture* texture = modelData->getTexture();
    JUTNameTab* textureName = modelData->getTextureName();
    JUT_ASSERT(146, texture != 0);
    JUT_ASSERT(147, textureName != 0);
    for (u16 i = 0; i < texture->getNum(); i++) {
        const char* name = textureName->getName(i);
        if (strcmp(name, "0_black") == 0) {
            texture->setResTIMG(i, *mDoGph_gInf_c::getFrameBufferTimg());
        } else if (strcmp(name, "1_black") == 0) {
            texture->setResTIMG(i, *mDoGph_gInf_c::getFrameBufferTimg());
        }
    }
    mDoExt_modelTexturePatch(modelData);
}

/* 801EB420-801EB444       .text loadModelData__FPUc */
J3DModelData* loadModelData(u8* i_data) {
    return J3DModelLoaderDataBase::loadBinaryDisplayList(i_data, 0x1020);
}

/* 801EB444-801EB464       .text loadAnmTransformData__FPUc */
J3DAnmTransform* loadAnmTransformData(u8* i_data) {
    return (J3DAnmTransform*)J3DAnmLoaderDataBase::load(i_data);
}

/* 801EB464-801EB6FC       .text __ct__10dmsg3_3d_cFv */
dmsg3_3d_c::dmsg3_3d_c() : field_0x48(NULL) {
    field_0x48 = mDoExt_createSolidHeapFromGameToCurrent(0x20000, 0x20);
    field_0x4 = field_0x48->alloc(0x1f40, 0x20);
    JKRArchive* arc = dComIfGp_getMsgArchive();
    JKRArchive::readTypeResource(field_0x4, 0x1f40, 'BDLM', "hukidashi_07.bdl", arc);
    DCStoreRangeNoSync(field_0x4, 0x1f40);
    field_0xc = field_0x48->alloc(0x1388, 0x20);
    arc = dComIfGp_getMsgArchive();
    JKRArchive::readTypeResource(field_0xc, 0x1388, 'BCK ', "hukidashi_07.bck", arc);
    DCStoreRangeNoSync(field_0xc, 0x1388);
    J3DModelData* modelData = loadModelData((u8*)field_0x4);
    JUT_ASSERT(213, modelData != 0);
    mModel = mDoExt_J3DModel__create(modelData, 0x80000, 0x37441422);
    JUT_ASSERT(218, mModel != 0);
    J3DAnmTransform* bck = loadAnmTransformData((u8*)field_0xc);
    JUT_ASSERT(221, bck != 0);
    int ok_bck = field_0x34.init(modelData, bck, 1, 0);
    JUT_ASSERT(228, ok_bck != 0);
    setDummyTexture();
    field_0x28.set(0, -0x8000, 0);
    field_0x10.set(1.0f, 1.0f, 1.0f);
    mModel->setBaseScale(field_0x10);
    set_mtx();
    mDoExt_adjustSolidHeap(field_0x48);
    mDoExt_restoreCurrentHeap();
}

/* 801EB6FC-801EB79C       .text __dt__10dmsg3_3d_cFv */
dmsg3_3d_c::~dmsg3_3d_c() {
    field_0x48->free(field_0x4);
    field_0x48->free(field_0xc);
    mDoExt_destroySolidHeap(field_0x48);
}

/* 801EB79C-801EB808       .text set_mtx__10dmsg3_3d_cFv */
void dmsg3_3d_c::set_mtx() {
    mDoMtx_stack_c::transS(0.0f, 0.0f, 0.0f);
    mDoMtx_stack_c::ZXYrotM(field_0x28);
    mModel->setBaseTRMtx(mDoMtx_stack_c::get());
}

/* 801EB808-801EB840       .text exec__10dmsg3_3d_cFv */
void dmsg3_3d_c::exec() {
    field_0x34.play();
    set_mtx();
}

/* 801EB840-801EB8DC       .text draw__10dmsg3_3d_cFv */
void dmsg3_3d_c::draw() {
    dComIfGd_setList2D();
    field_0x34.entry(mModel->getModelData());
    mDoExt_modelUpdateDL(mModel);
    field_0x34.remove(mModel->getModelData());
    dComIfGd_setList();
}

/* 801EB8DC-801EBA18       .text dMsg3_value_init__FP14sub_msg3_classUc */
void dMsg3_value_init(sub_msg3_class* i_this, u8 i_idx) {
    /* Nonmatching - 95.13%: all 79 instructions match in opcode and order except
     * that the four shadow-color copies (`0 | byte`, folded to mr) are emitted
     * interleaved before each text-color `or` instead of grouped after all four,
     * with a register permutation following from it. Probed per regalloc.md:
     * declaration order/reversal, uninit predecls, actor alias, split locals
     * (u8/u32, killed and rekilled), struct rereads - MWCC folds and coalesces
     * every same-value two-variable form back to this same IR. The or-group/
     * mr-group idiom exists nowhere else in the game (only the unimplemented
     * dMsg2 twin). Reassigning `color = 0` between the two groups is real code
     * (shadow text is black), not a liveness hack: without it, color stays
     * callee-saved across the calls and cc1/gc1 are rematerialized (83%). */
    static const u32 colorTable[] = {
        0x00000000, 0xB4000000, 0x82828200, 0x0000AA00, 0xF0F01E00,
        0x82FFFF00, 0x6400FF00, 0x50505000, 0xFFB40000,
    };
    char buf0[0x20];
    char buf2[0x20];
    char buf1[0x20];
    char buf3[0x20];
    u32 color = colorTable[i_this->field_0xea0];
    u8 b0 = i_this->screen[i_idx].field_0x290;
    u8 b1 = i_this->screen[i_idx].field_0x291;
    u8 b2 = i_this->screen[i_idx].field_0x292;
    u8 b3 = i_this->screen[i_idx].field_0x293;
    u32 cc0 = color | b0;
    u32 gc0 = color | b1;
    u32 cc1 = color | b2;
    u32 gc1 = color | b3;
    color = 0; // shadow text is drawn in black
    u32 cc2 = color | b0;
    u32 gc2 = color | b1;
    u32 cc3 = color | b2;
    u32 gc3 = color | b3;
    sprintf(buf0, "\033CC[%08x]\033GC[%08x]", cc0, gc0);
    sprintf(buf1, "\033CC[%08x]\033GC[%08x]", cc1, gc1);
    sprintf(buf2, "\033CC[%08x]\033GC[%08x]", cc2, gc2);
    sprintf(buf3, "\033CC[%08x]\033GC[%08x]", cc3, gc3);
    strcpy(i_this->output_text[i_idx], buf0);
    strcpy(i_this->output_ruby[i_idx], buf1);
    strcpy(i_this->output_textSdw[i_idx], buf2);
    strcpy(i_this->output_rubySdw[i_idx], buf3);
}

/* 801EBA18-801EBAB4       .text dMsg3_setString__FP14sub_msg3_classUc */
void dMsg3_setString(sub_msg3_class* i_this, u8 i_idx) {
    ((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->setString(i_this->output_text[i_idx]);
    ((J2DTextBox*)i_this->field_0xa5c[i_idx].pane)->setString(i_this->output_ruby[i_idx]);
    ((J2DTextBox*)i_this->field_0x9b4[i_idx].pane)->setString(i_this->output_textSdw[i_idx]);
    ((J2DTextBox*)i_this->field_0xb04[i_idx].pane)->setString(i_this->output_rubySdw[i_idx]);
}

/* 801EBAB4-801EBAD8       .text dMsg3_messagePaneShow__FP14sub_msg3_classUc */
void dMsg3_messagePaneShow(sub_msg3_class* i_this, u8 i_idx) {
    i_this->field_0x90c[i_idx].pane->show();
    i_this->field_0xa5c[i_idx].pane->show();
}

/* 801EBAD8-801EBAFC       .text dMsg3_messagePaneHide__FP14sub_msg3_classUc */
void dMsg3_messagePaneHide(sub_msg3_class* i_this, u8 i_idx) {
    i_this->field_0x90c[i_idx].pane->hide();
    i_this->field_0xa5c[i_idx].pane->hide();
}

J2DScreen* sScreen3[3];
J2DPicture* bbutton_icon3[8][3];
J2DPicture* bbutton_kage3[8][3];
s16 bbuttonTimer3[8][3];

dmsg3_3d_c* msg3d;
int dMsg3_popSpeed;
static dDlst_2DMSG3_c message;

/* 801EBAFC-801EBBD0       .text dMsg3_outFontHide__FUc */
void dMsg3_outFontHide(u8 i_idx) {
    for (int i = 0; i < 8; i++) {
        bbutton_icon3[i][i_idx]->hide();
        bbutton_kage3[i][i_idx]->hide();
        J2DPicture* icon = bbutton_icon3[i][i_idx];
        icon->mRotation = 0.0f;
        icon->calcMtx();
        J2DPicture* kage = bbutton_kage3[i][i_idx];
        kage->mRotation = 0.0f;
        kage->calcMtx();
        bbuttonTimer3[i][i_idx] = -1;
    }
}

/* 801EBBD0-801EBC08       .text dMsg3_arrowUpShow__FP14sub_msg3_class */
void dMsg3_arrowUpShow(sub_msg3_class* i_this) {
    fopMsgM_setInitAlpha(&i_this->field_0xbac[0]);
    fopMsgM_setInitAlpha(&i_this->field_0xbac[1]);
}

/* 801EBC08-801EBC40       .text dMsg3_arrowUpHide__FP14sub_msg3_class */
void dMsg3_arrowUpHide(sub_msg3_class* i_this) {
    fopMsgM_setNowAlphaZero(&i_this->field_0xbac[0]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xbac[1]);
}

/* 801EBC40-801EBC78       .text dMsg3_arrowDownShow__FP14sub_msg3_class */
void dMsg3_arrowDownShow(sub_msg3_class* i_this) {
    fopMsgM_setInitAlpha(&i_this->field_0xc1c[0]);
    fopMsgM_setInitAlpha(&i_this->field_0xc1c[1]);
}

/* 801EBC78-801EBCB0       .text dMsg3_arrowDownHide__FP14sub_msg3_class */
void dMsg3_arrowDownHide(sub_msg3_class* i_this) {
    fopMsgM_setNowAlphaZero(&i_this->field_0xc1c[0]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xc1c[1]);
}

/* 801EBCB0-801EBCE8       .text dMsg3_dotShow__FP14sub_msg3_class */
void dMsg3_dotShow(sub_msg3_class* i_this) {
    fopMsgM_setInitAlpha(&i_this->field_0xc8c[0]);
    fopMsgM_setInitAlpha(&i_this->field_0xc8c[1]);
}

/* 801EBCE8-801EBD20       .text dMsg3_dotHide__FP14sub_msg3_class */
void dMsg3_dotHide(sub_msg3_class* i_this) {
    fopMsgM_setNowAlphaZero(&i_this->field_0xc8c[0]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xc8c[1]);
}

static dDlst_2Dm_c board;

/* 801EBD20-801EBDE4       .text dMsg3_multiTexInit__FP14sub_msg3_class */
void dMsg3_multiTexInit(sub_msg3_class* i_this) {
    JKRArchive* arc = dComIfGp_getMsgArchive();
    JKRArchive::readTypeResource(i_this->Tex[0], 0x11800, 'TIMG', "hukidashi_0212.bti", arc);
    DCStoreRangeNoSync(i_this->Tex[0], 0x11800);
    arc = dComIfGp_getMsgArchive();
    JKRArchive::readTypeResource(i_this->Tex[1], 0x11800, 'TIMG', "hukidashi_07.bti", arc);
    DCStoreRangeNoSync(i_this->Tex[1], 0x11800);
    board.init((ResTIMG*)i_this->Tex[0], (ResTIMG*)i_this->Tex[1], 1.0f, 1.0f);
}

/* 801EBDE4-801EBE94       .text dMsg3_fontdataInit__FP14sub_msg3_class */
void dMsg3_fontdataInit(sub_msg3_class* i_Msg) {
    i_Msg->mx = mDoExt_getMesgFont();
    JUT_ASSERT(628, i_Msg->mx != 0);
    i_Msg->rx = mDoExt_getRubyFont();
    JUT_ASSERT(631, i_Msg->rx != 0);
}

/* 801EBE94-801EBED8       .text dMsg3_screenDataSet__FP14sub_msg3_classUc */
void dMsg3_screenDataSet(sub_msg3_class* i_this, u8 i_idx) {
    dMsg3_value_init(i_this, i_idx);
    dMsg3_setString(i_this, i_idx);
}

/* 801EBED8-801EC52C       .text dMsg3_screenDataInit__FP14sub_msg3_classUc */
void dMsg3_screenDataInit(sub_msg3_class* i_this, u8 i_idx) {
    // Read into field_0xeb4 at the end of the function but never assigned: retail reads it
    // uninitialized (f31 is saved by the prologue and never defined). The same bug is present in
    // the dMsg2 twin, so it has to be reproduced here to match.
    f32 fontSizeY;

    fopMsgM_setPaneData(&i_this->field_0x90c[i_idx], sScreen3[i_idx]->search('tx23'));
    fopMsgM_setPaneData(&i_this->field_0xa5c[i_idx], sScreen3[i_idx]->search('tx29'));
    fopMsgM_setPaneData(&i_this->field_0x9b4[i_idx], sScreen3[i_idx]->search('tx20'));
    fopMsgM_setPaneData(&i_this->field_0xb04[i_idx], sScreen3[i_idx]->search('tx26'));
    i_this->field_0x9b4[i_idx].pane->hide();
    i_this->field_0xb04[i_idx].pane->hide();
    fopMsgM_setPaneData(&i_this->field_0xcfc[i_idx], sScreen3[i_idx]->search('ms22'));
    fopMsgM_setPaneData(&i_this->field_0xda4[i_idx], sScreen3[i_idx]->search('ms20'));
    sScreen3[i_idx]->search('tx24')->hide();
    sScreen3[i_idx]->search('tx30')->hide();
    sScreen3[i_idx]->search('tx21')->hide();
    sScreen3[i_idx]->search('tx27')->hide();
    ((J2DPicture*)i_this->field_0xcfc[i_idx].pane)->setWhite(0);
    ((J2DPicture*)i_this->field_0xda4[i_idx].pane)->setWhite(0);

    if (i_idx == 0) {
        fopMsgM_setPaneData(&i_this->field_0xbac[0], sScreen3[i_idx]->search('yz21'));
        fopMsgM_setPaneData(&i_this->field_0xc1c[0], sScreen3[i_idx]->search('yz20'));
        fopMsgM_setPaneData(&i_this->field_0xc8c[0], sScreen3[i_idx]->search('dt20'));
        fopMsgM_setPaneData(&i_this->field_0xbac[1], sScreen3[i_idx]->search('yz23'));
        fopMsgM_setPaneData(&i_this->field_0xc1c[1], sScreen3[i_idx]->search('yz22'));
        fopMsgM_setPaneData(&i_this->field_0xc8c[1], sScreen3[i_idx]->search('dt21'));
        ((J2DPicture*)i_this->field_0xbac[1].pane)->setWhite(0xff);
        ((J2DPicture*)i_this->field_0xc1c[1].pane)->setWhite(0xff);
        ((J2DPicture*)i_this->field_0xc8c[1].pane)->setWhite(0xff);
    } else {
        sScreen3[i_idx]->search('yz21')->hide();
        sScreen3[i_idx]->search('yz20')->hide();
        sScreen3[i_idx]->search('dt20')->hide();
        sScreen3[i_idx]->search('yz23')->hide();
        sScreen3[i_idx]->search('yz22')->hide();
        sScreen3[i_idx]->search('dt21')->hide();
    }

    ((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->setFont(i_this->mx);
    ((J2DTextBox*)i_this->field_0xa5c[i_idx].pane)->setFont(i_this->rx);
    ((J2DTextBox*)i_this->field_0x9b4[i_idx].pane)->setFont(i_this->mx);
    ((J2DTextBox*)i_this->field_0xb04[i_idx].pane)->setFont(i_this->rx);

    J2DTextBox::TFontSize size;
    size.mSizeX = g_msgHIO.field_0x70;
    size.mSizeY = g_msgHIO.field_0x70;
    ((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->setFontSize(size);
    ((J2DTextBox*)i_this->field_0x9b4[i_idx].pane)->setFontSize(size);

    ((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->setCharSpace(-2.0f);
    ((J2DTextBox*)i_this->field_0xa5c[i_idx].pane)->setCharSpace(-1.0f);
    ((J2DTextBox*)i_this->field_0x9b4[i_idx].pane)->setCharSpace(-2.0f);
    ((J2DTextBox*)i_this->field_0xb04[i_idx].pane)->setCharSpace(-1.0f);

    ((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->setLineSpace(g_msgHIO.field_0x5e);
    ((J2DTextBox*)i_this->field_0x9b4[i_idx].pane)->setLineSpace(g_msgHIO.field_0x5e);

    i_this->field_0xeb0 = size.mSizeX;
    i_this->field_0xeb4 = fontSizeY;
}

/* 801EC52C-801EC638       .text dMsg3_ScreenDataValueInit__FP14sub_msg3_class */
void dMsg3_ScreenDataValueInit(sub_msg3_class* i_this) {
    J2DTextBox* box = (J2DTextBox*)i_this->field_0x90c[0].pane;
    f32 line_space = box->mLineSpace;
    i_this->field_0xeac = (int)(line_space / 2.0f);
    i_this->field_0xe90 = g_messageHIO.field_0x3c + box->getHeight();
    fopMsgM_paneTrans(&i_this->field_0x90c[0], 0.0f, 0.0f);
    fopMsgM_paneTrans(&i_this->field_0x90c[1], 0.0f, i_this->field_0xe90);
    fopMsgM_paneTrans(&i_this->field_0x90c[2], 0.0f, -i_this->field_0xe90);
    fopMsgM_setNowAlphaZero(&i_this->field_0xbac[0]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xbac[1]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xc1c[0]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xc1c[1]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xc8c[0]);
    fopMsgM_setNowAlphaZero(&i_this->field_0xc8c[1]);
    for (int i = 0; i < 3; i++) {
        dMsg3_messageDataInit(i_this, i);
    }
}

/* 801EC638-801EC690       .text dMsg3_stickInfoInit__FP14sub_msg3_class */
void dMsg3_stickInfoInit(sub_msg3_class* i_this) {
    // 0xB8 == g_mDoCPd_cpadInfo[3].mMainStickPosY (offset-derived; pad index unverified)
    if (g_mDoCPd_cpadInfo[0].mMainStickPosY > 0.7f || g_mDoCPd_cpadInfo[3].mMainStickPosY > 0.7f) {
        i_this->field_0xed9 = 1;
    } else if (g_mDoCPd_cpadInfo[0].mMainStickPosY < 0.7f || g_mDoCPd_cpadInfo[3].mMainStickPosY < 0.7f) {
        i_this->field_0xed9 = 2;
    } else {
        i_this->field_0xed9 = 0;
    }
}

/* 801EC690-801EC714       .text dMsg3_stickInfoCheck__FP14sub_msg3_class */
void dMsg3_stickInfoCheck(sub_msg3_class* i_this) {
    if (i_this->field_0xed9 == 1) {
        if (g_mDoCPd_cpadInfo[0].mMainStickPosY <= 0.0f || g_mDoCPd_cpadInfo[3].mMainStickPosY <= 0.0f) {
            i_this->field_0xed9 = 0;
        }
    } else if (i_this->field_0xed9 == 2) {
        if (g_mDoCPd_cpadInfo[0].mMainStickPosY >= 0.0f || g_mDoCPd_cpadInfo[3].mMainStickPosY >= 0.0f) {
            i_this->field_0xed9 = 0;
        }
    }
}

/* 801EC714-801EC84C       .text dMsg3_messageOut__FP14sub_msg3_classUci */
void dMsg3_messageOut(sub_msg3_class* i_this, u8 i_idx, int i_val) {
    i_this->field_0xec8[i_idx] = 0;
    dMsg3_messagePaneShow(i_this, i_idx);
    dMsg3_messageDataInit(i_this, i_idx);

    i_this->screen[i_idx].field_0x118 = 0;
    i_this->screen[i_idx].field_0x138 = 0;
    i_this->screen[i_idx].field_0x13C = i_val;

    dMsg3_yose_select(i_this, i_idx);
    i_this->screen[i_idx].field_0x299 = 1;
    dMsg3_setCharAlpha(i_this, i_idx);
    i_this->screen[i_idx].stringSet();

    for (int i = 0; i < 8; i++) {
        u8 num = i_this->screen[i_idx].field_0x281[i];
        u32 val = i_this->screen[i_idx].field_0x220[i];
        if (num != 0xff && bbuttonTimer3[i][i_idx] == -1) {
            fopMsgM_outFontSet(bbutton_icon3[i][i_idx], bbutton_kage3[i][i_idx],
                               &bbuttonTimer3[i][i_idx], val, num);
        }
    }

    dMsg3_setString(i_this, i_idx);
}

/* 801EC84C-801EC8CC       .text dMsg3_yose_select__FP14sub_msg3_classUc */
void dMsg3_yose_select(sub_msg3_class* i_this, u8 i_idx) {
    i_this->screen[i_idx].field_0x118 = i_this->screen[i_idx].stringLength();
    i_this->field_0xec8[i_idx] = i_this->screen[i_idx].field_0x130;
    i_this->screen[i_idx].field_0x130 = 0;
    i_this->screen[i_idx].stringShift();
    dMsg3_textPosition(i_this, i_idx);
}

/* 801EC8CC-801EC97C       .text dMsg3_textPosition__FP14sub_msg3_classUc */
void dMsg3_textPosition(sub_msg3_class* i_this, u8 i_idx) {
    /* Nonmatching - 99.55%: all 44 instructions match except the product's register
     * (retail r0 vs r7 here). The int must stay a named local passed to all four
     * shiftSet calls (each inline instance converts it separately, sharing the xoris
     * halves). Probed: inline expression x4 (aliasing reloads eac/ec8 per call, 30%),
     * f32 local / assignment-in-argument (single CSE'd conversion, 47%), named
     * operands with repeated register product (76%). A named short-lived int never
     * lands in r0; no lever found. */
    int val = i_this->field_0xeac * (2 - i_this->field_0xec8[i_idx]);
    ((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->shiftSet(0.0f, val);
    ((J2DTextBox*)i_this->field_0xa5c[i_idx].pane)->shiftSet(0.0f, val);
    ((J2DTextBox*)i_this->field_0x9b4[i_idx].pane)->shiftSet(0.0f, val);
    ((J2DTextBox*)i_this->field_0xb04[i_idx].pane)->shiftSet(0.0f, val);
}

/* 801EC97C-801EC9F0       .text dMsg3_rubySet__FP14sub_msg3_class */
void dMsg3_rubySet(sub_msg3_class* i_this) {
    if (i_this->mStatus == 5 || i_this->mStatus == 6 || i_this->mStatus == 7 || i_this->mStatus == 10) {
        for (int i = 0; i < 3; i++) {
            if (g_messageHIO.field_0x4b == 0) {
                i_this->field_0xa5c[i].pane->hide();
            } else {
                i_this->field_0xa5c[i].pane->show();
            }
        }
    }
}

/* 801EC9F0-801ECC08       .text dMsg3_arrowMove__FP14sub_msg3_class */
void dMsg3_arrowMove(sub_msg3_class* i_this) {
    i_this->field_0xeb8++;
    if (i_this->field_0xeb8 > 12) {
        i_this->field_0xeb8 -= 12;
    }

    i_this->field_0xc1c[0].pane->move((int)i_this->field_0xc1c[0].mPosTopLeftOrig.x,
                                      (int)i_this->field_0xc1c[0].mPosTopLeftOrig.y -
                                          abs(6 - i_this->field_0xeb8));
    i_this->field_0xc1c[1].pane->move((int)i_this->field_0xc1c[0].mPosTopLeftOrig.x,
                                      (int)i_this->field_0xc1c[0].mPosTopLeftOrig.y -
                                          abs(6 - i_this->field_0xeb8));
    i_this->field_0xbac[0].pane->move((int)i_this->field_0xbac[0].mPosTopLeftOrig.x,
                                      (int)i_this->field_0xbac[0].mPosTopLeftOrig.y +
                                          abs(6 - i_this->field_0xeb8));
    i_this->field_0xbac[1].pane->move((int)i_this->field_0xbac[0].mPosTopLeftOrig.x,
                                      (int)i_this->field_0xbac[0].mPosTopLeftOrig.y +
                                          abs(6 - i_this->field_0xeb8));
}

/* 801ECC08-801ECCE4       .text dMsg3_aimAlphaSqare__FP14sub_msg3_classii */
void dMsg3_aimAlphaSqare(sub_msg3_class* i_this, int i_max, int i_val) {
    /* Nonmatching - 99.55%: f4/f5 swapped on the two long-lived temps (255.0f and
     * 255.0f - brightness). Invariant under: locals (diff/ratio/result), const,
     * register, decl order/position, C-style casts, 0xff literal on either use,
     * operand order, ternary vs if/else clamp, store-through-local, named diff,
     * named/predeclared 255.0f (float temps re-coalesce under copy-prop, unlike
     * the GPR named-local lever that fixed setCharAlpha/outFontDraw). No inline is
     * involved (single .text section for this TU in frameworkD.map) and the twin
     * dMsg2_aimAlphaSqare (d_message.o, unmatched) shows the same retail alloc. */
    if (i_val < 0) {
        i_val = 0;
    } else if (i_val > i_max) {
        i_val = i_max;
    }
    f32 brightness = dMsg3_aimBrightness();
    i_this->field_0xea4 = 255.0f - (255.0f - brightness) * ((f32)i_val * (f32)i_val / ((f32)i_max * (f32)i_max));
}

/* 801ECCE4-801ECE04       .text dMsg3_aimAlphaSqrt__FP14sub_msg3_classii */
void dMsg3_aimAlphaSqrt(sub_msg3_class* i_this, int i_max, int i_val) {
    if (i_val < 0) {
        i_val = 0;
    } else if (i_val > i_max) {
        i_val = i_max;
    }
    f32 v = std::sqrtf((f32)i_val / (f32)i_max);
    f32 brightness = dMsg3_aimBrightness();
    i_this->field_0xea4 = 255.0f - (255.0f - brightness) * v;
}

/* 801ECE04-801ECEA0       .text dMsg3_kankyoBrightness__Fv */
int dMsg3_kankyoBrightness() {
    GXColorS10* col = dKy_Get_DifCol();
    return (int)(0.114f * col->b + (0.299f * col->r + 0.587f * col->g));
}

/* 801ECEA0-801ECEEC       .text dMsg3_aimBrightness__Fv */
u8 dMsg3_aimBrightness() {
    int brightness = dMsg3_kankyoBrightness();
    if ((u8)brightness > g_messageHIO.field_0x29) {
        return 0xff - (brightness - g_messageHIO.field_0x29);
    }
    return 0xff;
}

u8 dMsg3_tex_i4_color[240] = {
    0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x02, 0x02, 0x02, 0x03, 0x04, 0x06,
    0x07, 0x09, 0x0B, 0x0D, 0x0F, 0x12, 0x16, 0x1C, 0x22, 0x2A, 0x32, 0x39,
    0x41, 0x4B, 0x54, 0x5E, 0x67, 0x72, 0x7C, 0x87, 0x8F, 0x98, 0xA2, 0xAC,
    0xB3, 0xBB, 0xC2, 0xCA, 0xD0, 0xD8, 0xDD, 0xE1, 0xE7, 0xEA, 0xEE, 0xF1,
    0xF3, 0xF5, 0xF7, 0xF9, 0xFB, 0xFE, 0xFD, 0xFD, 0xFD, 0xFD, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFD, 0xFD, 0xFD,
    0xFD, 0xFB, 0xFB, 0xF9, 0xF7, 0xF5, 0xF3, 0xF1, 0xEE, 0xEA, 0xE7, 0xE1,
    0xDD, 0xD8, 0xD0, 0xC9, 0xC2, 0xBC, 0xB3, 0xAB, 0xA2, 0x99, 0x8F, 0x87,
    0x7C, 0x72, 0x68, 0x5E, 0x54, 0x4A, 0x41, 0x3A, 0x32, 0x2A, 0x22, 0x1D,
    0x15, 0x12, 0x0F, 0x0D, 0x0B, 0x09, 0x07, 0x05, 0x04, 0x04, 0x03, 0x02,
};

/* 801ECEEC-801ED2C8       .text dMsg3_setCharAlpha__FP14sub_msg3_classUc */
void dMsg3_setCharAlpha(sub_msg3_class* i_this, u8 i_idx) {
    /* Nonmatching - 99.19%: all 247 instructions match in opcode and order except the
     * clrlwi of i_idx, which lands three slots early (right after the lineSpace statement
     * instead of after the diff statement); no probed form moves it - the truncation is
     * hoisted there whether idx is the raw parameter or a named local of any type/const.
     * The former base-register rotation is fixed by the named `base` pointer below:
     * a named local is register-allocated after the anonymous CSE temps, which is what
     * puts the first clamp base at r7 (top of pool) like retail. The scroll term must be
     * spelled out twice (a `scroll` local sinks the mLineSpace conversion to its single
     * use), and the four alpha reads must be locals declared back-to-front (that is what
     * batches the four loads ahead of the four stores, in reverse). */
    int lineSpace = (int)((J2DTextBox*)i_this->field_0x90c[0].pane)->mLineSpace;

    f32 diff = i_this->field_0xcfc[0].mPosTopLeftOrig.y - i_this->field_0xda4[0].mPosTopLeftOrig.y;
    u8 idx = i_idx;
    f32 posY = diff + i_this->field_0x90c[idx].mPosTopLeft.y +
               (f32)(i_this->field_0xeac * (2 - i_this->field_0xec8[i_idx]));

    int textTop = (int)posY;
    int textY = textTop + lineSpace * i_this->field_0xec8[i_idx];
    int rubyTop = (int)(posY - g_messageHIO.field_0x38);
    int rubyY = rubyTop + lineSpace * i_this->field_0xec8[i_idx];

    if (textY < 0x3a) {
        int next = textY + i_this->mx->getHeight();
        if (textY >= 0) {
            i_this->field_0xedb[idx] = dMsg3_tex_i4_color[textY];
        } else {
            i_this->field_0xedb[idx] = 0;
        }
        if (next >= 0) {
            i_this->field_0xede[idx] = dMsg3_tex_i4_color[next];
        } else {
            i_this->field_0xede[idx] = 0;
        }
    } else if (textTop > 0xbb) {
        int next = textTop + i_this->mx->getHeight();
        if (textTop <= 0xef) {
            i_this->field_0xedb[idx] = dMsg3_tex_i4_color[textTop];
        } else {
            i_this->field_0xedb[idx] = 0;
        }
        if (next <= 0xef) {
            i_this->field_0xede[idx] = dMsg3_tex_i4_color[next];
        } else {
            i_this->field_0xede[idx] = 0;
        }
    } else {
        i_this->field_0xedb[idx] = 0xff;
        i_this->field_0xede[idx] = 0xff;
    }

    if (rubyY < 0x3a) {
        int next = rubyY + i_this->rx->getHeight();
        if (rubyY >= 0) {
            i_this->field_0xee1[idx] = dMsg3_tex_i4_color[rubyY];
        } else {
            i_this->field_0xee1[idx] = 0;
        }
        if (next >= 0) {
            i_this->field_0xee4[idx] = dMsg3_tex_i4_color[next];
        } else {
            i_this->field_0xee4[idx] = 0;
        }
    } else if (rubyTop > 0xbb) {
        int next = rubyTop + i_this->rx->getHeight();
        if (rubyTop <= 0xef) {
            i_this->field_0xee1[idx] = dMsg3_tex_i4_color[rubyTop];
        } else {
            i_this->field_0xee1[idx] = 0;
        }
        if (next <= 0xef) {
            i_this->field_0xee4[idx] = dMsg3_tex_i4_color[next];
        } else {
            i_this->field_0xee4[idx] = 0;
        }
    } else {
        i_this->field_0xee1[idx] = 0xff;
        i_this->field_0xee4[idx] = 0xff;
    }

    u8* base = (u8*)i_this + idx;
    if (base[0xedb] > (u8)i_this->field_0xea8) {
        base[0xedb] = i_this->field_0xea8;
    }
    if (i_this->field_0xede[idx] > (u8)i_this->field_0xea8) {
        i_this->field_0xede[idx] = i_this->field_0xea8;
    }
    if (i_this->field_0xee1[idx] > (u8)i_this->field_0xea8) {
        i_this->field_0xee1[idx] = i_this->field_0xea8;
    }
    if (i_this->field_0xee4[idx] > (u8)i_this->field_0xea8) {
        i_this->field_0xee4[idx] = i_this->field_0xea8;
    }

    u8 rubySdwAlpha = i_this->field_0xee4[idx];
    u8 rubyAlpha = i_this->field_0xee1[idx];
    u8 textSdwAlpha = i_this->field_0xede[idx];
    u8 textAlpha = base[0xedb];
    i_this->screen[idx].field_0x290 = textAlpha;
    i_this->screen[idx].field_0x291 = textSdwAlpha;
    i_this->screen[idx].field_0x292 = rubyAlpha;
    i_this->screen[idx].field_0x293 = rubySdwAlpha;
}

/* 801ED2C8-801ED37C       .text dMsg3_messageShow__FP14sub_msg3_class */
void dMsg3_messageShow(sub_msg3_class* i_this) {
    for (u8 i = 0; i < 3; i++) {
        dMsg3_screenDataSet(i_this, i);
    }

    if (i_this->field_0xec0 > 0) {
        dMsg3_messageOut(i_this, i_this->field_0xe98[0], i_this->field_0xec0 - i_this->entry.field_0x16);
    }

    dMsg3_messageOut(i_this, i_this->field_0xe98[1], i_this->field_0xec0);

    u8 idx = i_this->field_0xe98[1];
    // Same value as screen[idx].field_0x27C, but the raw offset form is required
    // to match codegen (lbzx indexed load vs lbz+add for the member-access form).
    if (((u8*)i_this)[idx * 0x2a0 + 0x394] == 7) {
        dMsg3_messageOut(i_this, i_this->field_0xe98[2], i_this->field_0xec0 + i_this->entry.field_0x16);
    }
}

/* 801ED37C-801ED4B4       .text dMsg3_messageDataInit__FP14sub_msg3_classi */
void dMsg3_messageDataInit(sub_msg3_class* i_this, int i_idx) {
    f32 charSpace0 = ((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->mCharSpace;
    f32 charSpace1 = ((J2DTextBox*)i_this->field_0xa5c[i_idx].pane)->mCharSpace;
    i_this->screen[i_idx].dataInit();
    i_this->screen[i_idx].field_0x3C = i_this->field_0xe5c;
    // Declared forward but assigned in reverse: the loads must come out back-to-front
    // while keeping the registers of forward declaration order.
    char* p6c;
    char* p78;
    char* p84;
    p84 = i_this->output_rubySdw[i_idx];
    p78 = i_this->output_textSdw[i_idx];
    p6c = i_this->output_ruby[i_idx];
    i_this->screen[i_idx].field_0x40 = i_this->screen[i_idx].field_0x60 = i_this->output_text[i_idx];
    i_this->screen[i_idx].field_0x44 = i_this->screen[i_idx].field_0x64 = p6c;
    i_this->screen[i_idx].field_0x48 = i_this->screen[i_idx].field_0x68 = p78;
    i_this->screen[i_idx].field_0x4C = i_this->screen[i_idx].field_0x6C = p84;
    i_this->screen[i_idx].font[0] = i_this->mx;
    i_this->screen[i_idx].font[1] = i_this->rx;
    i_this->screen[i_idx].field_0x11C = (int)charSpace0;
    i_this->screen[i_idx].field_0x124 = (int)charSpace1;
    i_this->screen[i_idx].field_0x120 = (int)((J2DTextBox*)i_this->field_0x90c[i_idx].pane)->mLineSpace;
    i_this->screen[i_idx].field_0x0C = (JMSMesgEntry_c*)((u8*)i_this + 0x100);
    i_this->screen[i_idx].field_0x144 = i_this->field_0xeb0;
    i_this->screen[i_idx].field_0x14C = i_this->field_0xeb4;
    i_this->screen[i_idx].field_0x128 = 0x1f7;
    i_this->screen[i_idx].field_0x12C = 0x1e6;
    i_this->screen[i_idx].field_0x29C = 0;
}

/* 801ED4B4-801ED608       .text dMsg3_stopProc__FP14sub_msg3_class */
BOOL dMsg3_stopProc(sub_msg3_class* i_this) {
    if (i_this->field_0xed9 == 0) {
        if (g_mDoCPd_cpadInfo[0].mMainStickPosY > 0.7f || g_mDoCPd_cpadInfo[3].mMainStickPosY > 0.7f) {
            if (i_this->field_0xec0 != 0) {
                u8 idx = i_this->field_0xe98[2];
                i_this->field_0xed9 = 1;
                dMsg3_screenDataSet(i_this, idx);
                i_this->field_0xebc = 3;
                i_this->field_0xec0 -= i_this->entry.field_0x16;
                i_this->mStatus = 5;
                JAIZelBasic::zel_basic->seStart(0x803);
            }
        } else if (g_mDoCPd_cpadInfo[0].mButtonTrig.a || g_mDoCPd_cpadInfo[0].mMainStickPosY < -0.7f ||
                   g_mDoCPd_cpadInfo[3].mMainStickPosY < -0.7f) {
            u8 idx = i_this->field_0xe98[0];
            i_this->field_0xed9 = 2;
            dMsg3_screenDataSet(i_this, idx);
            i_this->field_0xebc = 1;
            i_this->field_0xec0 += i_this->entry.field_0x16;
            i_this->mStatus = 5;
            JAIZelBasic::zel_basic->seStart(0x803);
        }
    } else {
        dMsg3_stickInfoCheck(i_this);
    }
    return TRUE;
}

/* 801ED608-801ED738       .text dMsg3_closewaitProc__FP14sub_msg3_class */
BOOL dMsg3_closewaitProc(sub_msg3_class* i_this) {
    if (i_this->field_0xed9 == 0) {
        if (g_mDoCPd_cpadInfo[0].mMainStickPosY > 0.7f || g_mDoCPd_cpadInfo[3].mMainStickPosY > 0.7f) {
            if (i_this->field_0xec0 != 0) {
                u8 idx = i_this->field_0xe98[2];
                i_this->field_0xed9 = 1;
                dMsg3_screenDataSet(i_this, idx);
                i_this->field_0xebc = 3;
                i_this->field_0xec0 -= i_this->entry.field_0x16;
                i_this->mStatus = 5;
                JAIZelBasic::zel_basic->seStart(0x803);
            }
        } else if (g_mDoCPd_cpadInfo[0].mButtonTrig.a || g_mDoCPd_cpadInfo[0].mMainStickPosY < -0.7f ||
                   g_mDoCPd_cpadInfo[3].mMainStickPosY < -0.7f) {
            i_this->field_0xed9 = 2;
            JAIZelBasic::zel_basic->seStart(0x80d);
            i_this->mStatus = 0x10;
        }
    } else {
        dMsg3_stickInfoCheck(i_this);
    }
    return TRUE;
}

/* 801ED738-801ED8A8       .text dMsg3_openProc__FP14sub_msg3_class */
BOOL dMsg3_openProc(sub_msg3_class* i_this) {
    if (i_this->field_0xe94 == 0) {
        dMsg3_messageOut(i_this, i_this->field_0xe98[1], i_this->field_0xec0);
        // Raw offset (lbzx) required to match; member access emits lbz+add here.
        if (((u8*)i_this)[i_this->field_0xe98[1] * 0x2a0 + 0x394] == 7) {
            dMsg3_messageOut(i_this, i_this->field_0xe98[2], i_this->field_0xec0 + i_this->entry.field_0x16);
        }
    } else if (i_this->field_0xe94 == dMsg3_popSpeed) {
        i_this->mStatus = ((u8*)i_this)[i_this->field_0xe98[1] * 0x2a0 + 0x394];
    }

    i_this->field_0xea8 = 255.0f * fopMsgM_valueIncrease(dMsg3_popSpeed, i_this->field_0xe94, 0);
    if (i_this->field_0xe94 != 0) {
        dMsg3_messageShow(i_this);
    }

    if (((u8*)i_this)[i_this->field_0xe98[1] * 0x2a0 + 0x394] == 7) {
        i_this->field_0xc1c[0].mNowAlpha = i_this->field_0xea8;
        i_this->field_0xc1c[1].mNowAlpha = i_this->field_0xea8;
    } else {
        i_this->field_0xc8c[0].mNowAlpha = i_this->field_0xea8;
        i_this->field_0xc8c[1].mNowAlpha = i_this->field_0xea8;
    }

    dMsg3_aimAlphaSqrt(i_this, dMsg3_popSpeed, i_this->field_0xe94);
    dComIfG_setBrightness(i_this->field_0xea4);
    i_this->field_0xe94++;
    return TRUE;
}

/* 801ED8A8-801EDA30       .text dMsg3_closeProc__FP14sub_msg3_class */
BOOL dMsg3_closeProc(sub_msg3_class* i_this) {
    if (i_this->field_0xe94 == 0) {
        for (u8 i = 0; i < 3; i++) {
            dMsg3_messagePaneHide(i_this, i);
            dMsg3_outFontHide(i);
        }
        JKRFileLoader::removeResource(i_this->head_p, NULL);
        i_this->mStatus = 0x12;
    }

    i_this->field_0xe94--;
    if (i_this->field_0xe94 < 0) {
        i_this->field_0xe94 = 0;
    }

    i_this->field_0xea8 = 255.0f * fopMsgM_valueIncrease(dMsg3_popSpeed, i_this->field_0xe94, 0);

    if (i_this->field_0xbac[0].mNowAlpha != 0) {
        i_this->field_0xbac[0].mNowAlpha = i_this->field_0xea8;
        i_this->field_0xbac[1].mNowAlpha = i_this->field_0xea8;
    }
    if (i_this->field_0xc1c[0].mNowAlpha != 0) {
        i_this->field_0xc1c[0].mNowAlpha = i_this->field_0xea8;
        i_this->field_0xc1c[1].mNowAlpha = i_this->field_0xea8;
    }
    if (i_this->field_0xc8c[0].mNowAlpha != 0) {
        i_this->field_0xc8c[0].mNowAlpha = i_this->field_0xea8;
        i_this->field_0xc8c[1].mNowAlpha = i_this->field_0xea8;
    }

    dMsg3_aimAlphaSqare(i_this, dMsg3_popSpeed, i_this->field_0xe94);
    dComIfG_setBrightness(i_this->field_0xea4);
    return TRUE;
}

/* 801EDA30-801EDE80       .text dMsg3_outwaitProc__FP14sub_msg3_class */
BOOL dMsg3_outwaitProc(sub_msg3_class* i_this) {
    if (i_this->field_0xebc == 1 || i_this->field_0xebc == 2) {
        i_this->field_0xec4 += 0xc;
    } else if (i_this->field_0xebc == 3 || i_this->field_0xebc == 4) {
        i_this->field_0xec4 -= 0xc;
    }

    if (i_this->field_0xec4 > 0x3fc) {
        i_this->field_0xec4 -= 0x7f8;
    } else if (i_this->field_0xec4 < -0x3fc) {
        i_this->field_0xec4 += 0x7f8;
    }

    if (i_this->field_0xebc == 1) {
        u8 idx = i_this->field_0xe98[0];
        for (int i = 0; i < 3; i++) {
            i_this->field_0x90c[i].mPosTopLeft.y -= 12.0f;
        }
        i_this->field_0xeda -= 0x55;

        if (i_this->field_0x90c[idx].mPosTopLeft.y < -i_this->field_0xe90) {
            i_this->field_0xebc = 2;

            u8 tmp = i_this->field_0xe98[1];
            i_this->field_0xe98[1] = i_this->field_0xe98[2];
            i_this->field_0xe98[2] = i_this->field_0xe98[0];
            i_this->field_0xe98[0] = tmp;

            if (((u8*)i_this)[i_this->field_0xe98[1] * 0x2a0 + 0x394] == 7) {
                dMsg3_messageOut(i_this, i_this->field_0xe98[2],
                                 i_this->field_0xec0 + i_this->entry.field_0x16);
            } else {
                dMsg3_messagePaneHide(i_this, i_this->field_0xe98[2]);
                dMsg3_outFontHide(i_this->field_0xe98[2]);
            }

            i_this->field_0xeda = 0;
            dMsg3_arrowUpHide(i_this);
            dMsg3_arrowDownHide(i_this);
            dMsg3_dotHide(i_this);
        }
    } else if (i_this->field_0xebc == 3) {
        u8 idx = i_this->field_0xe98[2];
        for (int i = 0; i < 3; i++) {
            i_this->field_0x90c[i].mPosTopLeft.y += 12.0f;
        }
        i_this->field_0xeda -= 0x7f;

        if (i_this->field_0x90c[idx].mPosTopLeft.y > i_this->field_0xcfc[0].mSizeOrig.y) {
            i_this->field_0xebc = 4;

            u8 tmp = i_this->field_0xe98[1];
            i_this->field_0xe98[1] = i_this->field_0xe98[0];
            i_this->field_0xe98[0] = i_this->field_0xe98[2];
            i_this->field_0xe98[2] = tmp;

            if (i_this->field_0xec0 > 0) {
                dMsg3_messageOut(i_this, i_this->field_0xe98[0],
                                 i_this->field_0xec0 - i_this->entry.field_0x16);
            } else {
                dMsg3_messagePaneHide(i_this, i_this->field_0xe98[0]);
                dMsg3_outFontHide(i_this->field_0xe98[0]);
            }

            i_this->field_0xeda = 0;
            dMsg3_arrowUpHide(i_this);
            dMsg3_arrowDownHide(i_this);
            dMsg3_dotHide(i_this);
        }
    } else if (i_this->field_0xebc == 2) {
        for (int i = 0; i < 3; i++) {
            i_this->field_0x90c[i].mPosTopLeft.y -= 12.0f;
        }
        i_this->field_0xeda += 0x2b;

        if (i_this->field_0x90c[i_this->field_0xe98[1]].mPosTopLeft.y <=
            i_this->field_0x90c[0].mPosTopLeftOrig.y) {
            i_this->field_0x90c[i_this->field_0xe98[0]].mPosTopLeft.y =
                i_this->field_0x90c[0].mPosTopLeftOrig.y - i_this->field_0xe90;
            i_this->field_0x90c[i_this->field_0xe98[1]].mPosTopLeft.y =
                i_this->field_0x90c[0].mPosTopLeftOrig.y;
            i_this->field_0x90c[i_this->field_0xe98[2]].mPosTopLeft.y =
                i_this->field_0x90c[0].mPosTopLeftOrig.y + i_this->field_0xe90;

            i_this->field_0xebc = 0;

            if (((u8*)i_this)[i_this->field_0xe98[1] * 0x2a0 + 0x394] == 7) {
                i_this->mStatus = 7;
                dMsg3_arrowDownShow(i_this);
            } else {
                i_this->mStatus = 0xe;
                dMsg3_dotShow(i_this);
            }

            i_this->field_0xeda = 0xff;
            if (i_this->field_0xec0 != 0) {
                dMsg3_arrowUpShow(i_this);
            }
        }
        dMsg3_messageShow(i_this);
    } else if (i_this->field_0xebc == 4) {
        for (int i = 0; i < 3; i++) {
            i_this->field_0x90c[i].mPosTopLeft.y += 12.0f;
        }
        i_this->field_0xeda += 0x25;

        if (i_this->field_0x90c[i_this->field_0xe98[1]].mPosTopLeft.y >=
            i_this->field_0x90c[0].mPosTopLeftOrig.y) {
            i_this->field_0x90c[i_this->field_0xe98[0]].mPosTopLeft.y =
                i_this->field_0x90c[0].mPosTopLeftOrig.y - i_this->field_0xe90;
            i_this->field_0x90c[i_this->field_0xe98[1]].mPosTopLeft.y =
                i_this->field_0x90c[0].mPosTopLeftOrig.y;
            i_this->field_0x90c[i_this->field_0xe98[2]].mPosTopLeft.y =
                i_this->field_0x90c[0].mPosTopLeftOrig.y + i_this->field_0xe90;

            i_this->field_0xebc = 0;
            i_this->mStatus = 7;
            i_this->field_0xeda = 0xff;
            dMsg3_arrowDownShow(i_this);
            if (i_this->field_0xec0 != 0) {
                dMsg3_arrowUpShow(i_this);
            }
        }
        dMsg3_messageShow(i_this);
    } else {
        dMsg3_messageShow(i_this);
    }

    return TRUE;
}

/* 801EDE80-801EDF18       .text draw__14dDlst_2DMSG3_cFv */
void dDlst_2DMSG3_c::draw() {
    J2DOrthoGraph* graf = dComIfGp_getCurrentGrafPort();
    graf->setPort();
    for (int i = 0; i < 3; i++) {
        sScreen3[i]->setScissor(true);
        sScreen3[i]->draw(0.0f, 0.0f, graf);
    }
    outFontDraw();
}

/* 801EDF18-801EE104       .text outFontDraw__14dDlst_2DMSG3_cFv */
void dDlst_2DMSG3_c::outFontDraw() {
    /* Nonmatching - 99.84%: all 123 instructions match; only two adds have their
     * commutative operands transposed (add r3,r28,r8 vs r8,r28 and add r4,r3,r4 vs
     * r4,r3), both canonicalized independently of source operand order - no lever
     * found. The former r4/r8 actor/pane permutation is fixed by the declaration
     * order below: MWCC allocates named locals after anonymous CSE temps, and the
     * last-declared named local gets the top scratch register, so `pane` must be
     * predeclared before `actor` for `actor` to land in r8 like retail. `off` must
     * be updated in place with `+=` (a plain `off = base + off` is renamed to a new
     * temp and the multi-def is what stops copy-prop folding the 0x118 into the
     * displacements). */
    J2DPane* clip = field_0x4->field_0xcfc[0].pane;
    f32 top = clip->mGlobalBounds.i.y;
    f32 bottom = clip->mGlobalBounds.f.y;

    for (int i = 0; i < 3; i++) {
        for (int k = 0; k < 8; k++) {
            // Ugly but matching: retail keeps the 0x118 screen offset on the k-side
            // index (addi k*4+0x118, bare struct-field offsets as displacements) and
            // shares this base across the four loads. Member access folds the 0x118
            // into the displacements (0x280/0x2bc/0x2f8) and drops that addi; the
            // named base is what lets the byte and word loads share it.
            J2DPane* pane;
            sub_msg3_class* actor = field_0x4;
            u8* base = (u8*)((u32)actor + i * 0x2a0);
            u8 num = base[k + 0x399];
            int off = k * 4 + 0x118;
            off += (int)base;
            int posX = *(s32*)(off + 0x168);
            int line = *(s32*)(off + 0x1a4);
            int size = *(s32*)(off + 0x1e0);
            if (num != 0xff) {
                pane = actor->field_0x90c[i].pane;
                int x = posX + pane->mGlobalBounds.i.x;
                int prod = actor->field_0xeac * ((2 - actor->field_0xec8[i]) + line * 2);
                int y = prod + pane->mGlobalBounds.i.y;
                u8 alpha = actor->field_0xea8;
                if (y > top && y < bottom - size) {
                    fopMsgM_outFontDraw(bbutton_icon3[k][i], bbutton_kage3[k][i], x, y, size,
                                        &bbuttonTimer3[k][i], alpha, num);
                }
            }
        }
    }
}

/* 801EE104-801EE218       .text dMsg3_Draw__FP14sub_msg3_class */
static BOOL dMsg3_Draw(sub_msg3_class* i_this) {
    for (int i = 0; i < 3; i++) {
        i_this->field_0x90c[i].mNowAlpha = i_this->field_0xea8;
        i_this->field_0xa5c[i].mNowAlpha = i_this->field_0xea8;
        i_this->field_0x9b4[i].mNowAlpha = i_this->field_0xea8;
        i_this->field_0xb04[i].mNowAlpha = i_this->field_0xea8;
        fopMsgM_setAlpha(&i_this->field_0x90c[i]);
        fopMsgM_setAlpha(&i_this->field_0xa5c[i]);
        fopMsgM_setAlpha(&i_this->field_0x9b4[i]);
        fopMsgM_setAlpha(&i_this->field_0xb04[i]);
    }

    fopMsgM_setAlpha(&i_this->field_0xbac[0]);
    fopMsgM_setAlpha(&i_this->field_0xbac[1]);
    fopMsgM_setAlpha(&i_this->field_0xc1c[0]);
    fopMsgM_setAlpha(&i_this->field_0xc1c[1]);
    fopMsgM_setAlpha(&i_this->field_0xc8c[0]);
    fopMsgM_setAlpha(&i_this->field_0xc8c[1]);

    dComIfGd_set2DOpa(&message);
    msg3d->draw();
    return TRUE;
}

/* 801EE218-801EE740       .text dMsg3_Execute__FP14sub_msg3_class */
static BOOL dMsg3_Execute(sub_msg3_class* i_this) {
    JKRHeap* oldHeap = mDoExt_setCurrentHeap(i_this->heap);
    msg3d->exec();

    if (i_this->mStatus == 2) {
        dMsg3_openProc(i_this);
    } else if (i_this->mStatus == 5) {
        dMsg3_outwaitProc(i_this);
    } else if (i_this->mStatus == 7) {
        dMsg3_stopProc(i_this);
    } else if (i_this->mStatus == 0xe) {
        dMsg3_closewaitProc(i_this);
    } else if (i_this->mStatus == 0x10) {
        dMsg3_closeProc(i_this);
    } else if (i_this->mStatus == 0x13) {
        fopMsgM_Delete(i_this);
    }

    dMsg3_arrowMove(i_this);

    for (int i = 0; i < 3; i++) {
        // Keeping these as f32 is what defers the f32->int conversions to the call sites
        // (retail CSEs each one into a callee-saved register there); int locals would
        // force both conversions eagerly at the declarations instead.
        f32 px = i_this->field_0x90c[i].mPosTopLeft.x + g_messageHIO.field_0x58;
        f32 py = i_this->field_0x90c[i].mPosTopLeft.y;
        i_this->field_0x90c[i].pane->move((int)px, (int)py);
        i_this->field_0xa5c[i].pane->move((int)px, (int)py - g_messageHIO.field_0x38);
        i_this->field_0x9b4[i].pane->move((int)px + 2, (int)py + 2);
        i_this->field_0xb04[i].pane->move((int)px + 2, ((int)py + 2) - g_messageHIO.field_0x38);
    }

    dMsg3_rubySet(i_this);

    for (int i = 0; i < 3; i++) {
        // The HIO colour fields are u8 placeholders in d_meter.h; retail reads each as a
        // 4-byte TColor (unaligned lwz), so they have to be re-read through a TColor cast.
        // Passing a u32 instead would add a TColor(u32) temporary per call. The pane
        // expressions must stay inline: a named J2DTextBox* local would be held across the
        // whole iteration instead of being reloaded per setter group.
        ((J2DTextBox*)i_this->field_0x90c[i].pane)
            ->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x5,
                           *(JUtility::TColor*)&g_messageHIO.field_0x5);
        ((J2DTextBox*)i_this->field_0xa5c[i].pane)
            ->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x1d,
                           *(JUtility::TColor*)&g_messageHIO.field_0x1d);
        ((J2DTextBox*)i_this->field_0x9b4[i].pane)
            ->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x11,
                           *(JUtility::TColor*)&g_messageHIO.field_0x11);
        ((J2DTextBox*)i_this->field_0xb04[i].pane)
            ->setFontColor(*(JUtility::TColor*)&g_messageHIO.field_0x11,
                           *(JUtility::TColor*)&g_messageHIO.field_0x11);

        ((J2DTextBox*)i_this->field_0x90c[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x9);
        ((J2DTextBox*)i_this->field_0xa5c[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x21);
        ((J2DTextBox*)i_this->field_0x9b4[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x15);
        ((J2DTextBox*)i_this->field_0xb04[i].pane)->setWhite(*(JUtility::TColor*)&g_messageHIO.field_0x15);

        ((J2DTextBox*)i_this->field_0x90c[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0xd);
        ((J2DTextBox*)i_this->field_0xa5c[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0x25);
        ((J2DTextBox*)i_this->field_0x9b4[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0x19);
        ((J2DTextBox*)i_this->field_0xb04[i].pane)->setBlack(*(JUtility::TColor*)&g_messageHIO.field_0x19);
    }

    dComIfGp_setMesgStatus(i_this->mStatus);
    mDoExt_setCurrentHeap(oldHeap);
    return TRUE;
}

/* 801EE740-801EE748       .text dMsg3_IsDelete__FP14sub_msg3_class */
static BOOL dMsg3_IsDelete(sub_msg3_class*) {
    return TRUE;
}

/* 801EE748-801EE904       .text dMsg3_Delete__FP14sub_msg3_class */
static BOOL dMsg3_Delete(sub_msg3_class* i_this) {
    dComIfGp_setMesgStatus(0);
    dComIfG_setBrightness(0xff);

    JKRHeap* oldHeap = mDoExt_setCurrentHeap(i_this->heap);

    for (int i = 0; i < 3; i++) {
        delete sScreen3[i];
    }

    i_this->heap->free(i_this->Tex[0]);
    i_this->heap->free(i_this->Tex[1]);

    mDoExt_removeMesgFont();
    mDoExt_removeRubyFont();

    for (int i = 0; i < 3; i++) {
        for (int k = 0; k < 8; k++) {
            delete bbutton_icon3[k][i];
            delete bbutton_kage3[k][i];
        }
        i_this->heap->free(i_this->output_text[i]);
        i_this->heap->free(i_this->output_ruby[i]);
        i_this->heap->free(i_this->output_textSdw[i]);
        i_this->heap->free(i_this->output_rubySdw[i]);
    }

    delete msg3d;
    msg3d = NULL;

    mDoExt_setCurrentHeap(oldHeap);
    i_this->heap->freeAll();

    dComIfGp_setHeapLockFlag(0);
    return TRUE;
}

/* 801EE904-801EEEFC       .text dMsg3_Create__FP9msg_class */
static cPhs_State dMsg3_Create(msg_class* i_msg) {
    /* Nonmatching - 99.45%: two prologue instructions swapped - the anonymous .bss
     * anchor (lis/addi into r28) is hoisted above the i_Msg param copy instead of
     * being emitted after it. Probed: static_cast, cast-per-access without the local
     * (ruled out - the retail JUT_ASSERT strings literally say "i_Msg->Tex[0] != 0",
     * proving the named local), declaration order swap with heapLock. Same
     * anchor/park emission-order family as the setCharAlpha clrlwi slot; no lever. */
    sub_msg3_class* i_Msg = (sub_msg3_class*)i_msg;

    u8 heapLock = dComIfGp_isHeapLockFlag();
    if (heapLock != 0 && heapLock != 9) {
        return cPhs_INIT_e;
    }

    i_Msg->heap = dComIfGp_getExpHeap2D();
    dComIfGp_setHeapLockFlag(9);
    JKRHeap* oldHeap = mDoExt_setCurrentHeap(i_Msg->heap);

    msg3d = new dmsg3_3d_c();

    for (u8 i = 0; i < 3; i++) {
        sScreen3[i] = new J2DScreen();
        sScreen3[i]->set("hukidashi_02.blo", dComIfGp_getMsgArchive());
    }

    i_Msg->Tex[0] = i_Msg->heap->alloc(0x11800, 0x20);
    JUT_ASSERT(2188, i_Msg->Tex[0] != 0);
    i_Msg->Tex[1] = i_Msg->heap->alloc(0x11800, 0x20);
    JUT_ASSERT(2190, i_Msg->Tex[1] != 0);

    dMsg3_fontdataInit(i_Msg);

    for (u8 i = 0; i < 3; i++) {
        for (int k = 0; k < 8; k++) {
            bbutton_icon3[k][i] = new J2DPicture("font_07_02.bti");
            bbutton_kage3[k][i] = new J2DPicture("font_07_02.bti");
            fopMsgM_blendInit(bbutton_icon3[k][i], "font_00.bti");
            fopMsgM_blendInit(bbutton_kage3[k][i], "font_00.bti");
            bbutton_icon3[k][i]->hide();
            bbutton_kage3[k][i]->hide();
            bbutton_icon3[k][i]->setAlpha(0);
            bbutton_kage3[k][i]->setAlpha(0);
            bbuttonTimer3[k][i] = -1;
        }
    }

    for (u8 i = 0; i < 3; i++) {
        i_Msg->output_text[i] = (char*)i_Msg->heap->alloc(0x3e9, 4);
        JUT_ASSERT(2213, i_Msg->output_text[i] != 0);
        i_Msg->output_ruby[i] = (char*)i_Msg->heap->alloc(0x3e9, 4);
        JUT_ASSERT(2216, i_Msg->output_ruby[i] != 0);
        i_Msg->output_textSdw[i] = (char*)i_Msg->heap->alloc(0x3e9, 4);
        JUT_ASSERT(2219, i_Msg->output_textSdw[i] != 0);
        i_Msg->output_rubySdw[i] = (char*)i_Msg->heap->alloc(0x3e9, 4);
        JUT_ASSERT(2222, i_Msg->output_rubySdw[i] != 0);
    }

    i_Msg->head_p = i_Msg->msgGet.getMesgHeader(i_Msg->mMsgNo);
    JUT_ASSERT(2227, i_Msg->head_p);
    i_Msg->field_0xe5c = i_Msg->msgGet.getMessage(i_Msg->head_p);
    i_Msg->entry = i_Msg->msgGet.getMesgEntry(i_Msg->head_p);
    i_Msg->field_0xe9c = (i_Msg->msgGet.mGroupID << 8) | i_Msg->msgGet.mResMsgNo;
    i_Msg->mStatus = 2;

    dMsg3_multiTexInit(i_Msg);

    for (u8 i = 0; i < 3; i++) {
        dMsg3_screenDataInit(i_Msg, i);
        dMsg3_screenDataSet(i_Msg, i);
        dMsg3_messagePaneHide(i_Msg, i);
    }

    dMsg3_ScreenDataValueInit(i_Msg);
    dMsg3_stickInfoInit(i_Msg);

    i_Msg->field_0xebc = 0;
    i_Msg->field_0xe98[0] = 2;
    i_Msg->field_0xe98[1] = 0;
    i_Msg->field_0xe98[2] = 1;
    dMsg3_popSpeed = g_messageHIO.field_0x3b;

    mDoExt_setCurrentHeap(oldHeap);
    message.setActorP(i_Msg);
    dComIfGp_setMesgStatus(i_Msg->mStatus);
    return cPhs_COMPLEATE_e;
}
