//
// Generated by dtk
// Translation Unit: d_operate_wind.cpp
//

#include "d/dolzel.h" // IWYU pragma: keep
#include "d/d_operate_wind.h"
#include "d/d_com_inf_game.h"
#include "d/d_kankyo_wether.h"
#include "d/d_lib.h"
#include "d/d_meter.h"
#include "d/d_s_play.h"
#include "f_op/f_op_msg_mng.h"
#include "JSystem/J2DGraph/J2DPicture.h"
#include "m_Do/m_Do_controller_pad.h"
#include "m_Do/m_Do_ext.h"
#include "JSystem/J2DGraph/J2DOrthoGraph.h"
#include "JSystem/J2DGraph/J2DScreen.h"
#include "JSystem/JKernel/JKRExpHeap.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "JSystem/JUtility/JUTAssert.h"
#include "SSystem/SComponent/c_phase.h"

static dOw_HIO_c g_owHIO;

/* 8021E58C-8021E5F8       .text __ct__9dOw_HIO_cFv */
dOw_HIO_c::dOw_HIO_c() {
    field_0x08 = 0x1e;
    field_0x0a = 0x5f;
    field_0x0c = 0x9b;
    field_0x0e = 0x10;
    field_0x18 = 100;
    field_0x10 = 0x78;
    field_0x12 = 0x32;
    field_0x04 = 7.0f;
    field_0x14 = 0x14;
    field_0x16 = 0x28;
}

void dDlst_Ow_main_c::drawLine(int width, f32 x1, f32 y1, f32 x2, f32 y2) {
    J2DDrawLine(x1, y1, x2, y2, color, width);
}

/* 8021E5F8-8021E6A4       .text draw__15dDlst_Ow_main_cFv */
void dDlst_Ow_main_c::draw() {
    J2DOrthoGraph* graf = dComIfGp_getCurrentGrafPort();
    graf->setPort();

    for (int i = 0; i < mLineMax; i++) {
        // drawLine(6, mX1[i], mY1[i], mX2[i], mY2[i]);
        J2DDrawLine(mX1[i], mY1[i], mX2[i], mY2[i], color, 6);
    }

    scrn->draw(0.0f, 0.0f, graf);
}

/* 8021E6A4-8021E708       .text draw__15dDlst_Ow_mask_cFv */
void dDlst_Ow_mask_c::draw() {
    J2DOrthoGraph* graf = dComIfGp_getCurrentGrafPort();
    graf->setPort();
    scrn->draw(0.0f, 0.0f, graf);
}

/* 8021E708-8021E7E4       .text dOw_angleRegular__15dOperate_wind_cFf */
int dOperate_wind_c::dOw_angleRegular(f32 angle) {
    if (angle < -247.5f)
        return 90;
    else if (angle < -202.5f)
        return 135;
    else if (angle < -157.5f)
        return 180;
    else if (angle < -112.5f)
        return 225;
    else if (angle < -67.5f)
        return 270;
    else if (angle < -22.5f)
        return 315;
    else if (angle < 22.5f)
        return 0;
    else if (angle < 67.5f)
        return 45;
    else if (angle < 112.5f)
        return 90;
    else if (angle < 157.5f)
        return 135;
    else if (angle < 202.5f)
        return 180;
    // missing end return
}

/* 8021E7E4-8021E974       .text dOw_stickControl__15dOperate_wind_cFis */
int dOperate_wind_c::dOw_stickControl(int ret, s16 ang) {
    s32 angi = abs(ang);
    if (ret == 0) {
        if (angi > 0x7000) {
            return 1;
        } else if (ang >= 0x5000) {
            return 2;
        } else if (ang <= -0x5000) {
            return 8;
        } else if (ang >= 0x3000) {
            return 3;
        } else if (ang <= -0x3000) {
            return 7;
        } else if (ang >= 0x1000) {
            return 4;
        } else if (ang <= -0x1000) {
            return 6;
        } else {
            return 5;
        }
    } else {
        if (angi > 0x7F80) {
            return 1;
        } else if (ang >= 0x5800 && ang <= 0x6800) {
            return 2;
        } else if (ang <= -0x5800 && ang >= -0x6800) {
            return 8;
        } else if (ang >= 0x3F80 && ang <= 0x4080) {
            return 3;
        } else if (ang <= -0x3F80 && ang >= -0x4080) {
            return 7;
        } else if (ang >= 0x1800 && ang <= 0x2800) {
            return 4;
        } else if (ang <= -0x1800 && ang >= -0x2800) {
            return 6;
        } else if (angi < 0x80) {
            return 5;
        }
    }

    return ret;
}

/* 8021E974-8021ED4C       .text screenSet__15dOperate_wind_cFv */
void dOperate_wind_c::screenSet() {
    /* Nonmatching */
}

/* 8021ED4C-8021EE9C       .text alphaSet__15dOperate_wind_cFf */
void dOperate_wind_c::alphaSet(f32 i_value) {
    fopMsgM_setNowAlpha(&field_0x0c[0], i_value);
    fopMsgM_setNowAlpha(&field_0x0c[1], i_value);
    fopMsgM_setNowAlpha(&field_0x0c[2], i_value);
    fopMsgM_setNowAlpha(&field_0x0c[3], i_value);
    fopMsgM_setNowAlpha(&field_0x54c, i_value);
    for (int i = 0; i < 2; i++) {
        fopMsgM_setNowAlpha(&field_0x124[i], i_value);
    }
    fopMsgM_setNowAlpha(&field_0x194, i_value);
    for (int i = 0; i < 4; i++) {
        fopMsgM_setNowAlpha(&field_0x1cc[i], i_value);
    }
    for (int i = 0; i < 8; i++) {
        fopMsgM_setNowAlpha(&field_0x2ac[i], i_value);
    }
    fopMsgM_setNowAlpha(&field_0x46c[0], i_value);
    fopMsgM_setNowAlpha(&field_0x554, i_value);
    field_0x8d4 = g_owHIO.field_0x18 * i_value;
}

/* 8021EE9C-8021F550       .text arrowColor1__15dOperate_wind_cFv */
void dOperate_wind_c::arrowColor1() {
    /* Nonmatching */
}

/* 8021F550-8021FBC0       .text arrowColor2__15dOperate_wind_cFv */
void dOperate_wind_c::arrowColor2() {
    /* Nonmatching */
}

/* 8021FBC0-80220360       .text maskColor__15dOperate_wind_cFv */
void dOperate_wind_c::maskColor() {
    /* Nonmatching */
}

/* 80220360-802207C8       .text arrowDirection__15dOperate_wind_cFv */
void dOperate_wind_c::arrowDirection() {
    /* Nonmatching */
}

/* 802207C8-802208C4       .text windSet__15dOperate_wind_cFv */
void dOperate_wind_c::windSet() {
    switch (field_0x8cc) {
    case 315:
        dKyw_tact_wind_set(0, -0x6000);
        break;
    case 0:
        dKyw_tact_wind_set(0, -0x8000);
        break;
    case 45:
        dKyw_tact_wind_set(0, 0x6000);
        break;
    case 90:
        dKyw_tact_wind_set(0, 0x4000);
        break;
    case 135:
        dKyw_tact_wind_set(0, 0x2000);
        break;
    case 180:
        dKyw_tact_wind_set(0, 0);
        break;
    case 225:
        dKyw_tact_wind_set(0, -0x2000);
        break;
    case 270:
        dKyw_tact_wind_set(0, -0x4000);
        break;
    }
}

/* 802208C4-8022098C       .text ringScale__15dOperate_wind_cFf */
void dOperate_wind_c::ringScale(f32 i_scale) {
    for (int i = 0; i < 4; i++) {
        if (i == 0) {
            field_0x46c[i].mPosCenter.x = field_0x8c0 + i_scale * (field_0x46c[i].mPosCenterOrig.x - field_0x8c0);
            field_0x46c[i].mPosCenter.y = field_0x8c4 + i_scale * (field_0x46c[i].mPosCenterOrig.y - field_0x8c4);
        } else {
            field_0x46c[i].mPosCenter.x = field_0x46c[i].mPosCenterOrig.x * i_scale;
            field_0x46c[i].mPosCenter.y = field_0x46c[i].mPosCenterOrig.y * i_scale;
        }
        fopMsgM_paneScaleXY(&field_0x46c[i], i_scale);
    }
}

/* 8022098C-80220A60       .text directionTrans__15dOperate_wind_cFf */
void dOperate_wind_c::directionTrans(f32 i_value) {
    f32 trans = 80.0f * i_value;
    fopMsgM_paneTrans(&field_0x0c[0], 0.0f, trans);
    fopMsgM_paneTrans(&field_0x0c[1], 0.0f, -trans);
    fopMsgM_paneTrans(&field_0x0c[2], trans, 0.0f);
    fopMsgM_paneTrans(&field_0x0c[3], -trans, 0.0f);
    fopMsgM_paneTrans(&field_0x1cc[0], 0.0f, trans);
    fopMsgM_paneTrans(&field_0x1cc[1], 0.0f, -trans);
    fopMsgM_paneTrans(&field_0x1cc[2], trans, 0.0f);
    fopMsgM_paneTrans(&field_0x1cc[3], -trans, 0.0f);
}

/* 80220A60-80220CD8       .text lineInit__15dOperate_wind_cFf */
void dOperate_wind_c::lineInit(f32 i_value) {
    f32 length = -((-172.0f - REG6_F(5)) * i_value);
    f32 diff = field_0x2ac[0].mPosTopLeftOrig.y - field_0x194.mPosCenterOrig.y;
    f32 radius = diff * i_value;
    f32 cx, cy, rad;
    f32 step = 360.0f / field_0x8ce;
    f32 angle = 11.25f;
    for (int i = 0; i < field_0x8ce; i++) {

        if (i % 2) {
            rad = 3.1415927f * ((101.25f + angle) / 180.0f);
            f32 s = sin(rad);
            cx = field_0x8c0 + radius * s;
            f32 c = cos(rad);
            cy = field_0x8c4 + radius * c;
        } else {
            rad = 3.1415927f * ((78.75f + angle) / 180.0f);
            f32 s = sin(rad);
            cx = field_0x8c0 + radius * s;
            f32 c = cos(rad);
            cy = field_0x8c4 + radius * c;
        }
        f32 rad2 = 3.1415927f * (angle / 180.0f);
        field_0x598[i] = cx + length * (f32)sin(rad2);
        field_0x660[i] = cy + length * (f32)cos(rad2);
        field_0x728[i] = 2.0f * cx - field_0x598[i];
        field_0x7f0[i] = 2.0f * cy - field_0x660[i];
        if (i % 2) {
            field_0x598[i] = cx;
            field_0x660[i] = cy;
        } else {
            field_0x728[i] = cx;
            field_0x7f0[i] = cy;
        }
        angle += step;
    }
}

/* 80220CD8-80220D80       .text lineDraw__15dOperate_wind_cFv */
void dOperate_wind_c::lineDraw() {
    JUtility::TColor color(0xFF, 0xFF, 0xFF, field_0x8d4);
    mMain->setLineColor(color);
    mMain->setLineMax(field_0x8ce);
    f32 x1, y1, x2, y2;
    for (int i = 0; i < field_0x8ce; i++) {
        y2 = field_0x7f0[i];
        x2 = field_0x728[i];
        y1 = field_0x660[i];
        dDlst_Ow_main_c* main = mMain;
        x1 = field_0x598[i];
        main->mX1[i] = x1;
        main->mY1[i] = y1;
        main->mX2[i] = x2;
        main->mY2[i] = y2;
    }
}

/* 80220D80-80220E18       .text arrowRotate__15dOperate_wind_cFP18fopMsgM_pane_classs */
void dOperate_wind_c::arrowRotate(fopMsgM_pane_class* i_pane, s16 i_ang) {
    if (i_ang < 0) {
        i_ang += 360;
    }
    if (i_ang > 360) {
        i_ang -= 360;
    }
    i_pane->pane->rotate(i_pane->mSizeOrig.x / 2.0f, i_pane->mSizeOrig.y / 2.0f, ROTATE_Z, (f32)i_ang);
}

/* 80220E18-80221090       .text initialize__15dOperate_wind_cFv */
void dOperate_wind_c::initialize() {
    field_0x8c8 = 0;
    field_0x8ca = 0;
    field_0x8ce = g_owHIO.field_0x0e;
    field_0x8d4 = 0;
    field_0x8d0 = 0;
    field_0x0c[4].mUserArea = 0;
    field_0x46c[0].mUserArea = 0;
    field_0x124[0].mUserArea = 30;
    field_0x124[1].mUserArea = 35;
    ((J2DPicture*)field_0x124[0].pane)->setCornerColor(0xFFFFFF96, 0x00FFFFFF, 0xFFFFFF96, 0x00FFFFFF);
    ((J2DPicture*)field_0x124[1].pane)->setCornerColor(0xFFFFFF96, 0x00FFFFFF, 0xFFFFFF96, 0x00FFFFFF);
    field_0x8c0 = field_0x46c[0].mPosTopLeftOrig.x + field_0x46c[0].mSizeOrig.x;
    field_0x8c4 = field_0x46c[0].mPosTopLeftOrig.y;
    cXyz* wind = dKyw_get_wind_vec();
    s16 angle = cM_atan2s(wind->x, wind->z) + 0x8000;
    field_0x8cc = dOw_angleRegular(180.0f * angle / 32768.0f - 90.0f);
    arrowRotate(&field_0x0c[4], field_0x8cc);
    arrowRotate(&field_0x194, field_0x8cc + 90);
    field_0x8b8 = stick->getValueStick();
    lineInit(0.0f);
}

/* 80221090-802213B0       .text _create__15dOperate_wind_cFv */
void dOperate_wind_c::_create() {
    scrn1 = new J2DScreen();
    JUT_ASSERT(0x3de, scrn1 != 0);
    scrn1->set("operate_wind.blo", dComIfGp_getWindResArchive());
    scrn2 = new J2DScreen();
    JUT_ASSERT(0x3e2, scrn2 != 0);
    scrn2->set("operate_wind_mask.blo", dComIfGp_getWindResArchive());
    stick = new STControl(5, 2, 3, 2, 1.0f, 1.0f, 0x1000, 0x2000);
    JUT_ASSERT(0x3e6, stick != 0);
    mMain = new dDlst_Ow_main_c();
    JUT_ASSERT(0x3e9, mMain != 0);
    mMain->setScreen(scrn1);
    mMask = new dDlst_Ow_mask_c();
    JUT_ASSERT(0x3ed, mMask != 0);
    mMask->setScreen(scrn2);
    screenSet();
    initialize();
}

/* 802213B0-8022147C       .text _delete__15dOperate_wind_cFv */
void dOperate_wind_c::_delete() {
    delete scrn1;
    delete scrn2;
    delete stick;
    delete mMain;
    delete mMask;
    dComIfGp_getWindResArchive()->removeResourceAll();
}

/* 8022147C-8022151C       .text _move__15dOperate_wind_cFv */
void dOperate_wind_c::_move() {
    if (!dMenu_flag()) {
        if (CPad_CHECK_TRIG_A(0)) {
            windSet();
            dComIfGp_setOperateWindChangeOff();
        } else if (CPad_CHECK_TRIG_B(0)) {
            dComIfGp_setOperateWindCancelOff();
        }
        arrowColor1();
        arrowColor2();
        maskColor();
        arrowDirection();
    }
}

/* 8022151C-8022163C       .text _draw__15dOperate_wind_cFv */
void dOperate_wind_c::_draw() {
    fopMsgM_setAlpha(&field_0x0c[0]);
    fopMsgM_setAlpha(&field_0x0c[1]);
    fopMsgM_setAlpha(&field_0x0c[2]);
    fopMsgM_setAlpha(&field_0x0c[3]);
    fopMsgM_setAlpha(&field_0x54c);
    for (int i = 0; i < 2; i++) {
        fopMsgM_setAlpha(&field_0x124[i]);
    }
    fopMsgM_setAlpha(&field_0x194);
    for (int i = 0; i < 4; i++) {
        fopMsgM_setAlpha(&field_0x1cc[i]);
    }
    for (int i = 0; i < 8; i++) {
        fopMsgM_setAlpha(&field_0x2ac[i]);
    }
    fopMsgM_setAlpha(&field_0x46c[0]);
    fopMsgM_setAlpha(&field_0x554);
    lineDraw();
    dComIfGd_set2DOpa(mMask);
    dComIfGd_set2DOpa(mMain);
}

/* 8022163C-802216F0       .text _open__15dOperate_wind_cFv */
bool dOperate_wind_c::_open() {
    bool set = false;
    if (field_0x8c8 < 10) {
        field_0x8c8++;
        f32 value = fopMsgM_valueIncrease(10, field_0x8c8, 0);
        alphaSet(value);
        ringScale(value);
        directionTrans(fopMsgM_valueIncrease(10, 10 - field_0x8c8, 0));
        lineInit(value);
    }
    if (field_0x8c8 >= 10) {
        set = true;
    }
    return set;
}

/* 802216F0-80221770       .text _close__15dOperate_wind_cFv */
bool dOperate_wind_c::_close() {
    s16 time = g_owHIO.field_0x18;
    bool set = false;
    if (field_0x8c8 > 0) {
        field_0x8c8--;
        alphaSet(fopMsgM_valueIncrease(time, field_0x8c8, 0));
    }
    if (field_0x8c8 <= 0) {
        set = true;
    }
    return set;
}

/* 80221770-80221830       .text _create__5dOw_cFv */
void dOw_c::_create() {
    /* Nonmatching */
    dOw_scrn = new dOperate_wind_c();
    JUT_ASSERT(0x478, dOw_scrn != 0);
    dOw_scrn->_create();
}

/* 80221830-80221880       .text _delete__5dOw_cFv */
void dOw_c::_delete() {
    /* Nonmatching */
    dOw_scrn->_delete();
    delete dOw_scrn;
}

bool dOw_c::_draw() {
    if (field_0x104) /* getStatus? */
        dOw_scrn->_draw();
    return true;
}

/* 80221880-802218B4       .text dOw_Draw__FP5dOw_c */
static BOOL dOw_Draw(dOw_c* i_this) {
    /* Nonmatching */
    return i_this->_draw();
}

void dOw_c::_close() {
    if (!dOw_scrn->_close()) {
        dOw_scrn->_move();
    } else {
        field_0x104 = 0;
        fopMsgM_Delete(this);
    }
}

void dOw_c::_open() {
    if (dOw_scrn->_open())
        dOw_scrn->_move();
}

/* 802218B4-802219A4       .text dOw_Execute__FP5dOw_c */
static BOOL dOw_Execute(dOw_c* i_this) {
    /* Nonmatching */
    static u8 wind_flag = dComIfGp_getOperateWind();
    JKRHeap* old_heap = mDoExt_setCurrentHeap(i_this->getHeap());
    if (dComIfGp_getOperateWind() == 2) {
        i_this->_open();
    } else {
        if (wind_flag == 2) {
            i_this->setTimer(g_owHIO.field_0x08);
        }
        i_this->_close();
    }
    wind_flag = dComIfGp_getOperateWind();
    mDoExt_setCurrentHeap(old_heap);
    return TRUE;
}

/* 802219A4-802219AC       .text dOw_IsDelete__FP5dOw_c */
static BOOL dOw_IsDelete(dOw_c* i_this) {
    return TRUE;
}

/* 802219AC-80221A04       .text dOw_Delete__FP5dOw_c */
static BOOL dOw_Delete(dOw_c* i_this) {
    JKRHeap* old_heap = mDoExt_setCurrentHeap(i_this->getHeap());
    i_this->_delete();
    mDoExt_setCurrentHeap(old_heap);
    fopMsgM_destroyExpHeap(i_this->getHeap());
    return TRUE;
}

/* 80221A04-80221AA0       .text dOw_Create__FP9msg_class */
static cPhs_State dOw_Create(msg_class* i_msg) {
    dOw_c* i_this = (dOw_c*)i_msg;

    JKRExpHeap* heap = fopMsgM_createExpHeap(20000);
    JUT_ASSERT(0x547, heap != 0);
    i_this->setHeap(heap);
    JKRHeap* old_heap = mDoExt_setCurrentHeap(i_this->getHeap());
    i_this->field_0x104 = 1; /* setStatus? */
    i_this->_create();
    mDoExt_setCurrentHeap(old_heap);
    return cPhs_COMPLEATE_e;
}
